version: '3.8'

services:

  db:
    container_name: dizi-izi-db
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      TZ: UTC
      PGTZ: UTC

  backend:
    container_name: backend
    build: ../dizi-izi-backend
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - static:/app/static/
      - media:/app/media/
    env_file:
      - .env
    depends_on:
      - db

  frontend:
    build: ../dizi-izi-frontend
    container_name: frontend
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:8000  # Замените на ваш URL бекенда
      - NODE_ENV=production

  nginx:
    image: nginx:1.21.3-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static:/var/html/static/
      - media:/var/html/media/
    depends_on:
      - backend
    restart: always

volumes:
  static:
  media:
  postgres_data:
